### PR TITLE
Gradle build script and NPE fix

### LINKED ISSUE #8: NPE when sending to player
[Location of NPE](https://github.com/troed/Courier/blob/master/src/se/troed/plugin/Courier/CourierCommands.java#L174)

Just installed the latest release and tried to /post to myself as well as to another player. Server log shows a NullPointerException, presumably on `o.getName()` as the API says it can return null in some cases.

### PR DESCRIPTION
**Pull request by cwc**
Fixes #8 

Based on #7; merging will merge them both.

### CODE REVIEW

**Comment by cwc** [comment]
I'll try to test these changes on the latest CraftBukkit as well as Spigot. My server is small but I can force my buds to send lots of letters :grinning:.

**Comment by cwc** [comment]
Everything seems to be working as intended with this changeset. The null guard comes into play when the server has been restarted, as there are OfflinePlayer objects returned that have UUIDs, but their names are unknown until they log in again. An offline player that has yet to log in during the current uptime is unable to be sent mail; once logged in, they can have mail sent to them even if logged out. I believe this is expected behavior.

**Comment by troed** [comment]
Excellent. I must confess that I don't get the gradle setup to create working artifacts but I can manually create a working .jar just as I did before so it's not issue as long as it helps others.

**Comment by cwc** [comment]
Yeah if you run `./gradlew build` in the project directory, it should spit out a Courier.jar in `./build/libs/`. If that doesn't work do let me know.

**Comment by troed** [comment]
Thanks, it was my IntelliJ-Gradle integration that didn't manage to do it from the UI. After having verified it worked from shell I could figure out what was wrong. Build looks fine - will merge soon and fix one other reported issue as well and then hopefully tag a v1.2.1.

**Pull request merged**
